---
version: 2
project_name: dologen
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    binary: dologen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - formats:
      - tar.gz
    files:
      - completions/*
      - README*
      - LICENSE*
homebrew_casks:
  - name: dologen
    repository:
      owner: containeroo
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    directory: Casks
    homepage: https://containeroo.ch
    description: Simple CLI tool to generate Docker config.json with registry credentials
    license: GPL-3.0-or-later
    binaries:
      - dologen
    completions:
      bash: completions/dologen.bash
      zsh: completions/dologen.zsh
    hooks:
      post:
        install: |
          if OS.mac?
            system "xattr", "-dr", "com.apple.quarantine", "#{staged_path}/dologen"
          end
    test: |
      system "#{binary}/dologen", "--version"
